### ISSUE TITLE
Sometimes a page hard-link 404s after a new deploy

### ISSUE THREAD

**Issue by marpaia** [osquery/osquery-site#26] opened 2018-01-25 16:55 UTC
Sometimes, if someone force-browses to a page after a deploy of the website, it will appear to 404. Browsing back to https://osquery.io usually fixes this, but we should dig into why this is happening. Perhaps the progressive web app is no longer up to date locally and doesn't gracefully handle the condition?

**Comment by groob** [comment] 2018-01-29 13:31
This is a problem because the entire react app is a single JS file and client side routing is used. If the user navigates to the server root, then the JS file is fetched and rendered. But if they were to navigate to a specific URL, that URL would always 404. 

Example: `curl https://osquery.io/downloads/official/2.11.2`

The react app uses a service worker to cache content locally for browsers, but that feature is not yet supported by Safari or Edge. 

A good explanation of the routing mechanism and the cause of this issue can be found in the create-react-app [README](https://github.com/facebook/create-react-app/blob/eee29075d64a4d3c2c5af4f4b9836e54e8f8bb3e/packages/react-scripts/template/README.md#serving-apps-with-client-side-routing). 

[This article](https://hugogiraudel.com/2017/05/13/using-create-react-app-on-netlify/) suggests we  can fix this problem for Netlify by replacing the `404.html` page with `index.html` This will cause every get request to fetch the JS app app and trigger the client side rendering. 
The solution is a clever workaround we should apply to fix the error for users immediately.
Long term we should transition to a build mechanism that creates static HTML pages to be served without requiring JS.

**Comment by groob** [comment] 2018-01-29 13:44
Looks like I missed the edit at the top of the article, which links to a netlify specific solution. 
https://www.netlify.com/docs/redirects/
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#netlify

**Comment by marpaia** [comment] 2018-10-16 16:38
This isn't fixed, so I'm going to open this back up.

**Comment by zwass** [comment] 2019-07-10 18:58
I believe #137 was a duplicate of this, and the issue is now fixed by #138.

**Closed by zwass** 2019-07-10 18:58 UTC
